- name: play level variables
  hosts: local
  connection: local # Ansible is connecting to localhost
  vars:
    COURSE: Ansible
    DURATION: 4hrs
    Trainer: joindevops trainer
  tasks:
  - name: print the course info
    vars:
      COURSE: Devosps
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duratioin: {{ DURATION }}, Trainer: {{ Trainer }}"